[package]
name = "main"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "atomicdex-auth"
path = "src/main.rs"

[dependencies]
bytes = "1.1.0"
captcha = "0.0.9"
chrono = "0.4.19"
futures-util = "0.3.21"
hyper = { version = "0.14.18", features = ["server", "http1", "http2", "tcp"] }
jsonwebtoken = "8.1.0"
lazy_static = "1.4.0"
serde = "1.0.137"
serde_json = "1.0.81"
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
