[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
futures-util = "0.3.21"
hyper = { version = "0.14.18", features = ["server", "http1", "http2", "tcp"] }
serde_json = "1.0.81"
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
